"""
Module: src/data/registry_loader.py

Purpose:
    Provide a reusable loader for the AAAI dataset registry created by
    02_build_eval_registry.py.

What this module does:
    1. Loads the canonical registry JSON file.
    2. Resolves relative dataset paths against the project root.
    3. Loads JSONL examples for named datasets and evaluation groups.
    4. Exposes helper methods so later training and evaluation scripts do not
       hardcode train/val/test paths or specific unseen cipher names.
    5. Centralizes dataset bookkeeping in one place for portability across
       local machines and cluster environments.

Why this exists:
    The earlier ICML pipeline embedded dataset paths and special-case cipher
    loading directly inside large training/evaluation scripts. This module
    separates dataset configuration from runtime logic, which improves
    reproducibility, clarity, and maintainability for the AAAI pipeline.

Expected input:
    - datasets/processed/eval_registry_*.json generated by
      scripts/02_build_eval_registry.py

Typical usage:
    from src.data.registry_loader import RegistryLoader

    loader = RegistryLoader.from_project_root(
        root='.',
        registry_path='datasets/processed/eval_registry_family_holdout_v1.json'
    )

    train_data = loader.load_dataset('train')
    id_eval = loader.load_group('primary_id')
    holdout_eval = loader.load_group('primary_cipher_holdout')
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


class RegistryLoader:
    """Load and access datasets described by the AAAI evaluation registry."""

    def __init__(self, registry_path: Path):
        self.registry_path = Path(registry_path).resolve()
        if not self.registry_path.exists():
            raise FileNotFoundError(f"Registry file not found: {self.registry_path}")

        self.registry = self._load_json(self.registry_path)
        self.project_root = self._infer_project_root()
        self.datasets_by_name = self._build_dataset_index()
        self.group_map = self.registry.get("evaluation_groups", {})

    @classmethod
    def from_project_root(cls, root: str = ".", registry_path: Optional[str] = None) -> "RegistryLoader":
        root_path = Path(root).resolve()
        if registry_path is None:
            registry_path = root_path / "datasets" / "processed" / "eval_registry_family_holdout_v1.json"
        else:
            registry_path = Path(registry_path)
            if not registry_path.is_absolute():
                registry_path = (root_path / registry_path).resolve()
        return cls(registry_path)

    @staticmethod
    def _load_json(path: Path) -> Dict[str, Any]:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    @staticmethod
    def _load_jsonl(path: Path) -> List[Dict[str, Any]]:
        with open(path, "r", encoding="utf-8") as f:
            return [json.loads(line) for line in f if line.strip()]

    def _infer_project_root(self) -> Path:
        # Deliberately ignore the registry's stored "project_root_abs": that
        # field is a snapshot of wherever the registry was *built* (e.g. a
        # local dev machine), not where it currently lives. Always derive
        # the root from this registry file's actual on-disk location so the
        # same registry JSON resolves correctly after being copied to the
        # cluster. Matches the approach already used in
        # 04_run_zero_shot_baseline.py's own infer_project_root().
        return self.registry_path.parent.parent.parent.resolve()

    def _build_dataset_index(self) -> Dict[str, Dict[str, Any]]:
        datasets = self.registry.get("datasets", {})
        index: Dict[str, Dict[str, Any]] = {}

        for key in ["train", "val", "test"]:
            entry = datasets.get(key)
            if entry:
                index[entry["name"]] = entry

        for entry in datasets.get("unseen", []):
            index[entry["name"]] = entry

        return index

    def resolve_dataset_path(self, dataset_name: str) -> Path:
        entry = self.get_dataset_entry(dataset_name)

        path_rel = entry.get("path_rel")
        path_abs = entry.get("path_abs")

        if path_rel:
            rel_path = (self.project_root / path_rel).resolve()
            if rel_path.exists():
                return rel_path

        if path_abs:
            abs_path = Path(path_abs).resolve()
            if abs_path.exists():
                return abs_path

        raise FileNotFoundError(
            f"Could not resolve dataset path for '{dataset_name}'. "
            f"Checked path_rel={path_rel!r}, path_abs={path_abs!r}."
        )

    def get_dataset_entry(self, dataset_name: str) -> Dict[str, Any]:
        if dataset_name not in self.datasets_by_name:
            available = ", ".join(sorted(self.datasets_by_name.keys()))
            raise KeyError(f"Unknown dataset '{dataset_name}'. Available: {available}")
        return self.datasets_by_name[dataset_name]

    def list_dataset_names(self) -> List[str]:
        return sorted(self.datasets_by_name.keys())

    def list_groups(self) -> List[str]:
        return sorted(self.group_map.keys())

    def load_dataset(self, dataset_name: str) -> List[Dict[str, Any]]:
        path = self.resolve_dataset_path(dataset_name)
        return self._load_jsonl(path)

    def load_group(self, group_name: str) -> Dict[str, List[Dict[str, Any]]]:
        if group_name not in self.group_map:
            available = ", ".join(sorted(self.group_map.keys()))
            raise KeyError(f"Unknown group '{group_name}'. Available: {available}")

        group_spec = self.group_map[group_name]

        if isinstance(group_spec, list):
            return {name: self.load_dataset(name) for name in group_spec}

        if isinstance(group_spec, dict):
            return {
                subgroup_name: self.load_many(dataset_names)
                for subgroup_name, dataset_names in group_spec.items()
            }

        raise TypeError(f"Unsupported group format for '{group_name}': {type(group_spec)}")

    def load_many(self, dataset_names: List[str]) -> List[Dict[str, Any]]:
        merged: List[Dict[str, Any]] = []
        for name in dataset_names:
            merged.extend(self.load_dataset(name))
        return merged

    def load_train(self) -> List[Dict[str, Any]]:
        return self.load_dataset("train")

    def load_val(self) -> List[Dict[str, Any]]:
        return self.load_dataset("val")

    def load_test(self) -> List[Dict[str, Any]]:
        return self.load_dataset("test")

    def load_primary_id(self) -> Dict[str, List[Dict[str, Any]]]:
        return self.load_group("primary_id")

    def load_primary_cipher_holdout(self) -> Dict[str, List[Dict[str, Any]]]:
        return self.load_group("primary_cipher_holdout")

    def load_all_core_eval(self) -> Dict[str, List[Dict[str, Any]]]:
        return self.load_group("all_core_eval")

    def get_split_summary(self) -> Dict[str, Any]:
        return self.registry.get("split_summary", {})

    def get_counts(self) -> Dict[str, Any]:
        return self.registry.get("counts", {})

    def describe(self) -> Dict[str, Any]:
        return {
            "registry_path": str(self.registry_path),
            "project_root": str(self.project_root),
            "tag": self.registry.get("tag"),
            "registry_version": self.registry.get("registry_version"),
            "dataset_names": self.list_dataset_names(),
            "groups": self.list_groups(),
            "counts": self.get_counts(),
        }


if __name__ == "__main__":
    loader = RegistryLoader.from_project_root()
    description = loader.describe()

    print("=" * 72)
    print("Registry Loader Summary")
    print("=" * 72)
    print(f"Registry path: {description['registry_path']}")
    print(f"Project root:  {description['project_root']}")
    print(f"Tag:           {description['tag']}")
    print(f"Version:       {description['registry_version']}")
    print(f"Datasets:      {', '.join(description['dataset_names'])}")
    print(f"Groups:        {', '.join(description['groups'])}")
    print(f"Counts:        {description['counts']}")

